name: iOS starter workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
    build:
      runs-on: macOS-latest
      steps:

      - name: Build
        run: |
          set -o pipefail
          xcodebuild build \
          -destination 'platform=iOS Simulator,name=iPhone 11 Pro' \
          | xcpretty
        
