name: iOS starter workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
    build:
      runs-on: macOS-latest
      steps:

      - name: Build
        run: |
           xcodebuild clean build -project Trippie.xcodeproj -scheme Trippie -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO

        
