name: iOS starter workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
    build:
      name: Build Project
      runs-on: macOS-latest
      steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Set Xcode version
        uses: actions/setup-xcode@v1.1
        with:
          xcode-version: 13.0

      - name: Build
        run: |
          set -o pipefail
          xcodebuild build \
          -scheme Trippie \
          -destination 'platform=iOS Simulator,name=iPhone 11 Pro' \
          | xcpretty
        
